<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcb93f8fcefd46a27b5071318493b4620
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcb93f8fcefd46a27b5071318493b4620::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcb93f8fcefd46a27b5071318493b4620::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitcb93f8fcefd46a27b5071318493b4620::$classMap;

        }, null, ClassLoader::class);
    }
}
